name: 'Deploy'
description: 'Deploy the token list to S3 bucket.'
inputs:
  environment:
    description: 'Deployment environment (e.g., Test, CI).'
    required: true
    type: string
  bucket:
    description: 'AWS S3 bucket for backups.'
    required: true
    type: string
runs:
  using: 'composite'
  steps:
    - name: Deploy (Test folder)
      shell: bash
      if: ${{ inputs.environment == 'Test' }}
      run: aws s3 sync ./src/ s3://${{ inputs.bucket }}/TestFolder --exclude "*" --include "FullList/*.json" --include "ArbTokenLists/*.json"

    - name: Deploy
      shell: bash
      if: ${{ inputs.environment == 'CI' }}
      run: aws s3 sync ./src/ s3://${{ inputs.bucket }} --exclude "*" --include "FullList/*.json" --include "ArbTokenLists/*.json" --acl "public-read"
