name: 'Generate Orbit Chains Data'
description: 'Generate orbit chains data JSON file'

runs:
  using: 'composite'
  steps:
    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Generate Orbit Chains Data
      id: generate-data
      shell: bash
      run: npm run generate:orbitChainsData

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: orbit-chains-data
        path: 'src/Assets/orbitChainsData.json'
