name: 'Generate Orbit Chains Data'
description: 'Generate orbit chains data JSON file'

runs:
  using: 'composite'
  steps:
    - name: Generate Orbit Chains Data
      id: generate-data
      shell: bash
      run: yarn generate:orbitChainsData

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: orbitChainsData/json
        path: 'src/Assets/'
      continue-on-error: true
