name: 'Download Orbit Chains Data'
description: 'Download orbit chains data artifact'

runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v3

    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        name: orbit-chains-data-${{ github.sha }}
        path: 'src/Assets/orbitChainsData.json'
