name: 'Download Orbit Chains Data'
description: 'Download orbit chains data artifact'

runs:
  using: 'composite'
  steps:
    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        name: orbitChainsData.json
        path: 'src/Assets/'
