name: CI

on:
  pull_request:
    branches: ['master']
  push:
    branches: ['master']
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  install:
    name: 'Install'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Check cache for "node_modules"
        id: cache
        uses: martijnhols/actions-cache/check@v3
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-yarn-${{ hashFiles('yarn.lock') }}

      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: yarn install --frozen-lockfile

      - name: Save "node_modules" to cache
        if: steps.cache.outputs.cache-hit != 'true'
        uses: martijnhols/actions-cache/save@v3
        with:
          path: '**/node_modules'
          key: ${{ steps.cache.outputs.primary-key }}

  generate-orbit-chains-data:
    name: 'Generate Orbit Chains'
    runs-on: ubuntu-latest
    needs: install
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/restore-cache
      - uses: ./.github/actions/generate-orbit-chains-data

  check-formatting:
    name: 'Check Formatting'
    runs-on: ubuntu-latest
    needs: [install, generate-orbit-chains-data]
    steps:
      - uses: actions/checkout@v3

      - uses: ./.github/actions/restore-cache
      - uses: ./.github/actions/restore-orbit-chains-data

      - name: Check formatting with Prettier
        run: yarn prettier:check

  integration-test:
    name: 'Integration tests'
    runs-on: ubuntu-latest
    environment: CI
    needs: [install, generate-orbit-chains-data]
    env:
      INFURA_KEY: '${{ secrets.INFURA_KEY }}'
      MAINNET_RPC: 'https://mainnet.infura.io/v3/${{ secrets.INFURA_KEY }}'
      SEPOLIA_RPC: 'https://sepolia.infura.io/v3/${{ secrets.INFURA_KEY }}'
      L2_GATEWAY_SUBGRAPH_URL: '${{ secrets.L2_GATEWAY_SUBGRAPH_URL }}'
      L2_GATEWAY_SEPOLIA_SUBGRAPH_URL: '${{ secrets.L2_GATEWAY_SEPOLIA_SUBGRAPH_URL }}'

    steps:
      - uses: actions/checkout@v3

      - uses: ./.github/actions/restore-orbit-chains-data
      - uses: ./.github/actions/restore-cache

      - name: Test
        run: yarn test:integration

  unit-test:
    name: 'Unit tests'
    runs-on: ubuntu-latest
    environment: CI
    needs: [install, generate-orbit-chains-data]
    env:
      INFURA_KEY: '${{ secrets.INFURA_KEY }}'
      MAINNET_RPC: 'https://mainnet.infura.io/v3/${{ secrets.INFURA_KEY }}'
      SEPOLIA_RPC: 'https://sepolia.infura.io/v3/${{ secrets.INFURA_KEY }}'
      L2_GATEWAY_SUBGRAPH_URL: '${{ secrets.L2_GATEWAY_SUBGRAPH_URL }}'
      L2_GATEWAY_SEPOLIA_SUBGRAPH_URL: '${{ secrets.L2_GATEWAY_SEPOLIA_SUBGRAPH_URL }}'

    steps:
      - uses: actions/checkout@v3

      - uses: ./.github/actions/restore-cache
      - uses: ./.github/actions/restore-orbit-chains-data

      - name: Test
        run: yarn test:unit

  generate-token-lists:
    uses: ./.github/workflows/generate-token-lists.yml
    with:
      environment: 'Test'
    secrets: inherit
