name: Cron

on:
  pull_request:
    branches: ['master']
  push:
    branches: ['master']
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  install:
    name: 'Install'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Check cache for "node_modules"
        id: cache
        uses: martijnhols/actions-cache/check@v3
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-yarn-${{ hashFiles('yarn.lock') }}

      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: yarn install --frozen-lockfile

      - name: Save "node_modules" to cache
        if: steps.cache.outputs.cache-hit != 'true'
        uses: martijnhols/actions-cache/save@v3
        with:
          path: '**/node_modules'
          key: ${{ steps.cache.outputs.primary-key }}

  generate-token-list:
    name: 'Generate token list'
    runs-on: ubuntu-latest
    needs: install
    env:
      INFURA_KEY: '${{ secrets.INFURA_KEY }}'
      MAINNET_RPC: 'https://mainnet.infura.io/v3/${{ secrets.INFURA_KEY }}'
      GOERLI_RPC: 'https://goerli.infura.io/v3/${{ secrets.INFURA_KEY }}'

    steps:
      - uses: actions/checkout@v3

      - uses: ./.github/actions/restore-cache

      - name: Generate
        run: yarn generate:all

  upload-S3:
    name: 'Upload to S3'
    runs-on: ubuntu-latest
    needs: generate-token-list

    steps:
      - name: Upload
        uses: shallwefootball/s3-upload-action@master
        with:
          aws_key_id: ${{ secrets.AWS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
          aws_bucket: ${{ secrets.AWS_BUCKET }}
          source_dir: '/build'
          destination_dir: '' # Upload to root directory
