name: Cron

on:
  pull_request:
    branches: ['master']
  push:
    branches: ['master']
  schedule:
    - cron: '0/10 * * * *'

jobs:
  generate-token-lists:
    uses: ./.github/workflows/generate-token-lists.yml
    with:
      environment: 'CI'
    secrets: inherit

  test:
    runs-on: ubuntu-latest
    needs: [generate-token-lists]
    steps:
      - name: debug
        run: echo ${{ job.generate-token-lists.outputs.commands }}
