name: Cron

on:
  schedule:
    - cron: '0/10 * * * *'

jobs:
  generate-token-lists:
    uses: ./.github/workflows/generate-token-lists.yml
    with:
      environment: 'CI'
      firstTimeGeneration: false
    secrets: inherit
