name: Generate new orbit chain token list

on:
  schedule:
    # Every day at 9:00
    - cron: '0 9 * * *'

jobs:
  generate-token-lists:
    uses: ./.github/workflows/generate-token-lists.yml
    with:
      environment: 'Test'
    secrets: inherit
