name: Generate new orbit chain token list

# on:
#   schedule:
#     # Every day at 9:00
#     - cron: '0 9 * * *'
on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize

jobs:
  generate-token-lists:
    uses: ./.github/workflows/generate-token-lists.yml
    with:
      environment: 'Test'
      firstTimeGeneration: true
    secrets: inherit
